ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST:  mongodb-dev.girisha.online
REDIS_HOST: redis-dev.girisha.online
CATALOGUE_HOST : catalogue.backend_alb-dev.girisha.online
RABBITMQ_HOST: rabbitmq-dev.girisha.online
MYSQL_HOST: mysql-dev.girisha.online
USER_HOST : user.backend_alb-dev.girisha.online
CART_HOST: cart.backend_alb-dev.girisha.online
PAYMENT_HOST: payment.backend_alb-dev.girisha.online
SHIPPING_HOST: shipping.backend_alb-dev.girisha.online
